name: "OpenAI PR Reviewer"

concurrency:
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}-${{
    github.event_name == 'pull_request_review_comment' && 'pr_comment' || 'pr' }}

on:
  pull_request:
  pull_request_review_comment:
    types: ["created"]

permissions:
  contents: "read"
  pull-requests: "write"

jobs:
  review:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "fluxninja/openai-pr-reviewer@latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_comment_lgtm: false
          review_simple_changes: false
